In [ ]:
import cv2

face_cascade = cv2.CascadeClassifier("C:\\Users\\GOHIL\\anaconda3\\Lib\\site-packages\\cv2\\data\\haarcascade_frontalface_default.xml")

img = cv2.imread("C:\\Users\\GOHIL\\Pictures\\Saved Pictures\\sample.jpg")

gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img,scaleFactor = 1.05, minNeighbors=5)

print(type(faces))

print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 3)

# resized = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))

cv2.imshow("gray",img)

cv2.waitKey(0)

cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[797 380  38  38]
 [443 215 106 106]
 [909 355  50  50]
 [495 683  48  48]
 [542 851  40  40]
 [825 555  56  56]
 [578 482  38  38]
 [395 962  64  64]]
